local helpers = require("tests.helpers")
local Anchor = require("shaerk.anchor")

describe("anchor", function()
  it("returns the range it was created with", function()
    local buf = helpers.buf({ "a", "b", "c" })
    local a = Anchor.mark(buf, 1, 2)
    local srow, erow = a:range()
    assert.are.equal(1, srow)
    assert.are.equal(2, erow)
    assert.is_true(a:valid())
  end)

  it("shifts down when lines are inserted above", function()
    local buf = helpers.buf({ "a", "b", "c" })
    local a = Anchor.mark(buf, 1, 2)
    vim.api.nvim_buf_set_lines(buf, 0, 0, false, { "x", "y" })
    local srow, erow = a:range()
    assert.are.equal(3, srow)
    assert.are.equal(4, erow)
  end)

  it("applies replacement at the shifted position", function()
    local buf = helpers.buf({ "a", "b", "c" })
    local a = Anchor.mark(buf, 1, 2)
    vim.api.nvim_buf_set_lines(buf, 0, 0, false, { "x" })
    a:apply({ "B1", "B2" })
    assert.are.same(
      { "x", "a", "B1", "B2", "c" },
      vim.api.nvim_buf_get_lines(buf, 0, -1, false)
    )
  end)

  it("becomes invalid when the region is deleted", function()
    local buf = helpers.buf({ "a", "b", "c" })
    local a = Anchor.mark(buf, 1, 2)
    vim.api.nvim_buf_set_lines(buf, 1, 2, false, {})
    assert.is_false(a:valid())
  end)

  it("treats an empty range as an insert point and stays valid", function()
    local buf = helpers.buf({ "a", "b" })
    local a = Anchor.mark(buf, 1, 1)
    assert.is_true(a:valid())
    a:apply({ "NEW" })
    assert.are.same({ "a", "NEW", "b" }, vim.api.nvim_buf_get_lines(buf, 0, -1, false))
  end)

  it("marks a range that reaches the last line", function()
    local buf = helpers.buf({ "a", "b" })
    local a = Anchor.mark(buf, 0, 2)
    a:apply({ "only" })
    assert.are.same({ "only" }, vim.api.nvim_buf_get_lines(buf, 0, -1, false))
  end)

  it("replaces in a single undo entry", function()
    local buf = helpers.buf({ "a", "b", "c" })
    vim.api.nvim_set_current_buf(buf)
    local a = Anchor.mark(buf, 1, 2)
    a:apply({ "B1", "B2" })
    vim.cmd("silent undo")
    assert.are.same({ "a", "b", "c" }, vim.api.nvim_buf_get_lines(buf, 0, -1, false))
  end)

  it("clear removes the extmark", function()
    local buf = helpers.buf({ "a" })
    local a = Anchor.mark(buf, 0, 1)
    a:clear()
    assert.is_false(a:valid())
  end)

  it("a line inserted at the start row stays outside the range", function()
    local buf = helpers.buf({ "a", "b", "c" })
    local a = Anchor.mark(buf, 0, 2)
    vim.api.nvim_buf_set_lines(buf, 0, 0, false, { "header" })
    local srow, erow = a:range()
    assert.are.same({ "a", "b" }, vim.api.nvim_buf_get_lines(buf, srow, erow, false))
  end)
end)
