local helpers = require("tests.helpers")
local contract = require("shaerk.contract")

--- @param text string
--- @return string path
local function file_with(text)
  local path = helpers.tmpfile()
  helpers.write(path, text)
  return path
end

describe("contract.parse", function()
  it("parses an ok result", function()
    local path = file_with('{"v":1,"status":"ok","lang":"lua","note":"done"}\n\nlocal x = 1\nreturn x\n')
    local res, err = contract.parse(path)
    assert.is_nil(err)
    assert.are.equal("ok", res.status)
    assert.are.equal("lua", res.lang)
    assert.are.equal("done", res.note)
    assert.are.equal("local x = 1\nreturn x", res.body)
  end)

  it("keeps blank lines inside the body", function()
    local path = file_with('{"v":1,"status":"ok","lang":"lua"}\n\nlocal a = 1\n\nlocal b = 2\n')
    local res = contract.parse(path)
    assert.are.equal("local a = 1\n\nlocal b = 2", res.body)
  end)

  it("preserves absolute indentation", function()
    local path = file_with('{"v":1,"status":"ok","lang":"lua"}\n\n    local x = 1\n')
    local res = contract.parse(path)
    assert.are.equal("    local x = 1", res.body)
  end)

  it("strips a markdown fence around the body", function()
    local path = file_with('{"v":1,"status":"ok","lang":"lua"}\n\n```lua\nlocal x = 1\n```\n')
    local res = contract.parse(path)
    assert.are.equal("local x = 1", res.body)
  end)

  it("tolerates CRLF line endings", function()
    local path = file_with('{"v":1,"status":"ok","lang":"lua"}\r\n\r\nlocal x = 1\r\n')
    local res, err = contract.parse(path)
    assert.is_nil(err)
    assert.are.equal("local x = 1", res.body)
  end)

  it("tolerates a missing blank separator line", function()
    local path = file_with('{"v":1,"status":"ok","lang":"lua"}\nlocal x = 1\n')
    local res = contract.parse(path)
    assert.are.equal("local x = 1", res.body)
  end)

  it("parses refused without a body", function()
    local path = file_with('{"v":1,"status":"refused","note":"needs another file"}\n')
    local res, err = contract.parse(path)
    assert.is_nil(err)
    assert.are.equal("refused", res.status)
    assert.are.equal("needs another file", res.note)
    assert.is_nil(res.body)
  end)

  it("parses no_change", function()
    local path = file_with('{"v":1,"status":"no_change","note":"already correct"}\n')
    local res, err = contract.parse(path)
    assert.is_nil(err)
    assert.are.equal("no_change", res.status)
  end)

  it("reports no_file when the file is missing", function()
    local res, err = contract.parse(helpers.tmpfile())
    assert.is_nil(res)
    assert.are.equal("no_file", err)
  end)

  it("reports no_file when the file is empty", function()
    local res, err = contract.parse(file_with(""))
    assert.is_nil(res)
    assert.are.equal("no_file", err)
  end)

  it("reports bad_header on non-json first line", function()
    local res, err = contract.parse(file_with("here is your code\n\nlocal x = 1\n"))
    assert.is_nil(res)
    assert.are.equal("bad_header", err)
  end)

  it("reports bad_header on a wrong version", function()
    local res, err = contract.parse(file_with('{"v":2,"status":"ok","lang":"lua"}\n\nlocal x = 1\n'))
    assert.is_nil(res)
    assert.are.equal("bad_header", err)
  end)

  it("reports bad_header on a missing version", function()
    local res, err = contract.parse(file_with('{"status":"ok","lang":"lua"}\n\nlocal x = 1\n'))
    assert.is_nil(res)
    assert.are.equal("bad_header", err)
  end)

  it("reports bad_header on an unknown status", function()
    local res, err = contract.parse(file_with('{"v":1,"status":"maybe","lang":"lua"}\n\nlocal x = 1\n'))
    assert.is_nil(res)
    assert.are.equal("bad_header", err)
  end)

  it("reports bad_header when ok has no lang", function()
    local res, err = contract.parse(file_with('{"v":1,"status":"ok"}\n\nlocal x = 1\n'))
    assert.is_nil(res)
    assert.are.equal("bad_header", err)
  end)

  it("reports bad_header when refused has no note", function()
    local res, err = contract.parse(file_with('{"v":1,"status":"refused"}\n'))
    assert.is_nil(res)
    assert.are.equal("bad_header", err)
  end)

  it("reports bad_header when ok has an empty body", function()
    local res, err = contract.parse(file_with('{"v":1,"status":"ok","lang":"lua"}\n\n   \n'))
    assert.is_nil(res)
    assert.are.equal("bad_header", err)
  end)

  it("truncates an overlong note to 200 chars", function()
    local long = string.rep("x", 300)
    local path = file_with(string.format('{"v":1,"status":"refused","note":"%s"}\n', long))
    local res = contract.parse(path)
    assert.are.equal(200, #res.note)
  end)
end)

describe("contract.instructions", function()
  it("embeds the tmp path and the version", function()
    local text = contract.instructions("/tmp/abc.out")
    assert.is_truthy(text:find("/tmp/abc.out", 1, true))
    assert.is_truthy(text:find('"v":1', 1, true))
  end)
end)
